# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: base_types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("base_types.proto", :syntax => :proto3) do
    add_message "base_types.Empty" do
    end
    add_message "base_types.Health" do
      optional :status, :bool, 1
      optional :message, :string, 2
    end
    add_message "base_types.Output" do
      optional :status, :bool, 1
      optional :message, :string, 2
    end
  end
end

module BaseTypes
  Empty = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("base_types.Empty").msgclass
  Health = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("base_types.Health").msgclass
  Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("base_types.Output").msgclass
end
