# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user.proto

require 'google/protobuf'

require_relative '../base_types/base_types_pb'
require 'user_types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user.proto", :syntax => :proto3) do
  end
end

module GrpcUser
end
