# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user_types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("user_types.proto", :syntax => :proto3) do
    add_message "grpc_user.TokenRequest" do
      optional :token, :string, 1
    end
    add_message "grpc_user.UserRequest" do
      optional :id, :int64, 1
    end
    add_message "grpc_user.User" do
      optional :id, :int64, 1
      optional :userid, :string, 2
      optional :name, :string, 3
      optional :email, :string, 4
      optional :phone_number, :string, 5
      optional :role, :string, 6
      optional :status, :bool, 7
      optional :password_digest, :string, 8
      optional :enable_two_factors, :bool, 9
    end
    add_message "grpc_user.UserProfile" do
      optional :user, :message, 1, "grpc_user.User"
      optional :user_type, :string, 2
      optional :account_type, :string, 3
      optional :id_number, :string, 4
      optional :id_issue_date, :string, 5
      optional :id_issue_location, :string, 6
      optional :tax_number, :string, 7
      optional :address, :string, 8
      optional :date_of_birth, :string, 9
      optional :company, :string, 10
      optional :rep_name, :string, 11
      optional :rep_phone, :string, 12
      optional :rep_email, :string, 13
      optional :ref_name, :string, 14
      optional :ref_phone, :string, 15
      optional :ref_email, :string, 16
    end
    add_message "grpc_user.UserProfiles" do
      repeated :user_profiles, :message, 1, "grpc_user.UserProfile"
    end
  end
end

module GrpcUser
  TokenRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_user.TokenRequest").msgclass
  UserRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_user.UserRequest").msgclass
  User = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_user.User").msgclass
  UserProfile = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_user.UserProfile").msgclass
  UserProfiles = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("grpc_user.UserProfiles").msgclass
end
