# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: user.proto for package 'grpc_user'

require 'grpc'
require 'user_pb'

module GrpcUser
  module UserService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpc_user.UserService'

      rpc :verify_token, ::GrpcUser::TokenRequest, ::GrpcUser::User
      rpc :get_user, ::GrpcUser::UserRequest, ::GrpcUser::UserProfile
      rpc :get_all_users, ::GrpcUser::TokenRequest, ::GrpcUser::UserProfiles
      rpc :create_user, ::GrpcUser::User, ::BaseTypes::Output
      rpc :delete_user, ::GrpcUser::User, ::BaseTypes::Output
    end

    Stub = Service.rpc_stub_class
  end
end
