# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order.proto

require 'google/protobuf'

require_relative '../base_types/base_types_pb'
require 'order_types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order.proto", :syntax => :proto3) do
  end
end

module Order
end
