# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: order_types.proto

require 'google/protobuf'

require 'google/protobuf/timestamp_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("order_types.proto", :syntax => :proto3) do
    add_message "order.Product" do
      optional :id, :sint32, 1
      optional :cn, :string, 2
      optional :quantity, :int32, 3
      optional :type, :string, 4
      optional :version, :string, 5
    end
    add_message "order.Order" do
      optional :order_id, :int64, 1
      optional :region_id, :int32, 2
      optional :duration, :sint32, 3
      optional :approval_step, :sint32, 4
      optional :contract_no, :string, 5
      optional :start_at, :message, 6, "google.protobuf.Timestamp"
      optional :end_at, :message, 7, "google.protobuf.Timestamp"
      optional :user_id, :int64, 8
      repeated :computes, :message, 9, "order.Compute"
    end
    add_message "order.Compute" do
      optional :idx, :sint32, 1
      repeated :products, :message, 2, "order.Product"
    end
    add_message "order.OrderRequest" do
      optional :order_id, :int64, 1
      optional :order_idx, :sint32, 2
    end
    add_message "order.ApprovalRequest" do
      optional :user_id, :int64, 1
      optional :contract_code, :string, 2
      repeated :computes, :message, 3, "order.Compute"
    end
    add_message "order.Approval" do
      optional :approved, :bool, 1
    end
  end
end

module Order
  Product = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.Product").msgclass
  Order = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.Order").msgclass
  Compute = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.Compute").msgclass
  OrderRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.OrderRequest").msgclass
  ApprovalRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.ApprovalRequest").msgclass
  Approval = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("order.Approval").msgclass
end
