# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: vm.proto

require 'google/protobuf'

require_relative '../base_types/base_types_pb'
require 'vm_types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("vm.proto", :syntax => :proto3) do
  end
end

module GrpcVm
end
