# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: vm.proto for package 'grpc_vm'

require 'grpc'
require 'vm_pb'

module GrpcVm
  module VmService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'grpc_vm.VmService'

      rpc :create_vm, ::GrpcVm::VM, ::BaseTypes::Output
      rpc :delete_vm, ::GrpcVm::VM, ::BaseTypes::Output
    end

    Stub = Service.rpc_stub_class
  end
end
